name: E2E Tests
on:
  schedule:
    - cron:  '0 6 * * 1-5'
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test that contrib tests can run
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version:
          - "2.x"
          - "3.0.x"
          - "4.0.x"
    steps:
      - uses: actions/checkout@v5

      # We always use DDEV, so download it.
      - name: Install ddev
        run: curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh
      - name: Start ddev
        run: ddev start
      - name: Require a module
        run: ddev composer require drupal/gutenberg:${{ matrix.version }}-dev
      - name: Run all the tests
        run: ddev exec phpunit web/modules/contrib/gutenberg
