name: E2E Tests
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test:
    name: Test that contrib tests can run
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # We always use DDEV, so download it.
      - name: Install ddev
        run: curl -LO https://raw.githubusercontent.com/drud/ddev/master/scripts/install_ddev.sh && bash install_ddev.sh
      - name: Start ddev
        run: ddev start
      - name: Require a module
        run: ddev composer require drupal/gutenberg:2.x-dev
      - name: Run all the tests
        run: ddev exec phpunit web/modules/contrib/gutenberg
      - name: Run some core tests
        run: ddev exec phpunit web/core/modules/book/tests/src/FunctionalJavascript
